[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip STM32G431CB"
rustflags = [
    "-C", "linker=flip-link",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
    "-C", "link-arg=--nmagic",
]

[build]
target = "thumbv7em-none-eabihf"

# Compile-time defmt filter. Unset means all `defmt::*` macros are stripped.
[env]
DEFMT_LOG = "info"